### ISSUE TITLE
REFACTOR Application To Adjust Currency Conversion on Insertion

### ISSUE THREAD

**Issue by florinIacob** [tudorgrig/my-money-tracker#107]
When the USER inserts an income or an expense, the Currency Conversion Rate should be for the creation date of the record, NOT the Currency Rate of the Current Time.

**Comment by tudorgrig** [comment]
The currency must be converted on this cases:
1. On **creation of new expense/income**.
2. On **expense/income update** if amount, creationDate _or_ currency has changed _and_ user did not update the expense with his own default currency
3. On **inserting recurrent expense/income**
4. On **statistics view if expenses retrieved don't have data for the user's default currency.**
